// <auto-generated />
using System;
using BD.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BD.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20241101191736_BD2")]
    partial class BD2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BD.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "TW",
                            Name = "Тайвань"
                        },
                        new
                        {
                            Id = 2,
                            Code = "CN",
                            Name = "Китай"
                        },
                        new
                        {
                            Id = 3,
                            Code = "RU",
                            Name = "Россия"
                        },
                        new
                        {
                            Id = 4,
                            Code = "DE",
                            Name = "Германия"
                        },
                        new
                        {
                            Id = 5,
                            Code = "JP",
                            Name = "Япония"
                        },
                        new
                        {
                            Id = 6,
                            Code = "US",
                            Name = "США"
                        },
                        new
                        {
                            Id = 7,
                            Code = "CH",
                            Name = "Швейцария"
                        });
                });

            modelBuilder.Entity("BD.Models.Details", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("Capacity")
                        .HasColumnType("double precision");

                    b.Property<int>("CountryId")
                        .HasColumnType("integer");

                    b.Property<double?>("Electric_current")
                        .HasColumnType("double precision");

                    b.Property<double?>("Inductance")
                        .HasColumnType("double precision");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("integer");

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxOperating_Temp")
                        .HasColumnType("integer");

                    b.Property<int?>("MinOperating_Temp")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("Operating_voltage")
                        .HasColumnType("double precision");

                    b.Property<int>("Part_typeId")
                        .HasColumnType("integer");

                    b.Property<double?>("Power")
                        .HasColumnType("double precision");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<double?>("Resistance")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("Part_typeId");

                    b.ToTable("Details");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            ManufacturerId = 1,
                            MaterialId = 2,
                            MaxOperating_Temp = 155,
                            MinOperating_Temp = -55,
                            Model = "CF-100",
                            Name = "Резистор углеродистый",
                            Operating_voltage = 500.0,
                            Part_typeId = 2,
                            Power = 1.0,
                            Price = 9.0,
                            Resistance = 1.0
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            ManufacturerId = 1,
                            MaterialId = 2,
                            MaxOperating_Temp = 155,
                            MinOperating_Temp = -55,
                            Model = "CF-100",
                            Name = "Резистор углеродистый",
                            Operating_voltage = 500.0,
                            Part_typeId = 2,
                            Power = 1.0,
                            Price = 9.0,
                            Resistance = 100.0
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 1,
                            ManufacturerId = 1,
                            MaterialId = 2,
                            MaxOperating_Temp = 155,
                            MinOperating_Temp = -55,
                            Model = "CF-100",
                            Name = "Резистор углеродистый",
                            Operating_voltage = 500.0,
                            Part_typeId = 2,
                            Power = 1.0,
                            Price = 9.0,
                            Resistance = 510.0
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 1,
                            ManufacturerId = 3,
                            MaterialId = 2,
                            MaxOperating_Temp = 275,
                            MinOperating_Temp = -55,
                            Model = "AH-100",
                            Name = "Резистор силовой",
                            Operating_voltage = 1900.0,
                            Part_typeId = 2,
                            Power = 100.0,
                            Price = 1540.0,
                            Resistance = 0.10000000000000001
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 1,
                            ManufacturerId = 3,
                            MaterialId = 2,
                            MaxOperating_Temp = 275,
                            MinOperating_Temp = -55,
                            Model = "AH-100",
                            Name = "Резистор силовой",
                            Operating_voltage = 1900.0,
                            Part_typeId = 2,
                            Power = 100.0,
                            Price = 1530.0,
                            Resistance = 1.5
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 1,
                            ManufacturerId = 3,
                            MaterialId = 2,
                            MaxOperating_Temp = 275,
                            MinOperating_Temp = -55,
                            Model = "AH-100",
                            Name = "Резистор силовой",
                            Operating_voltage = 1900.0,
                            Part_typeId = 2,
                            Power = 100.0,
                            Price = 1540.0,
                            Resistance = 1000.0
                        },
                        new
                        {
                            Id = 7,
                            CountryId = 1,
                            ManufacturerId = 1,
                            MaterialId = 1,
                            MaxOperating_Temp = 125,
                            MinOperating_Temp = -55,
                            Model = "3006",
                            Name = "Резистор подстроечный",
                            Operating_voltage = 1000.0,
                            Part_typeId = 3,
                            Power = 0.75,
                            Price = 150.0,
                            Resistance = 100.0
                        },
                        new
                        {
                            Id = 8,
                            CountryId = 1,
                            ManufacturerId = 1,
                            MaterialId = 1,
                            MaxOperating_Temp = 150,
                            MinOperating_Temp = -65,
                            Model = "3224",
                            Name = "Резистор подстроечный",
                            Operating_voltage = 600.0,
                            Part_typeId = 3,
                            Power = 0.25,
                            Price = 200.0,
                            Resistance = 1000.0
                        },
                        new
                        {
                            Id = 9,
                            CountryId = 1,
                            ManufacturerId = 1,
                            MaterialId = 1,
                            MaxOperating_Temp = 150,
                            MinOperating_Temp = -65,
                            Model = "3266",
                            Name = "Резистор подстроечный",
                            Operating_voltage = 600.0,
                            Part_typeId = 3,
                            Power = 0.25,
                            Price = 220.0,
                            Resistance = 50.0
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 0.10000000000000001,
                            CountryId = 2,
                            ManufacturerId = 2,
                            MaterialId = 3,
                            MaxOperating_Temp = 85,
                            MinOperating_Temp = -25,
                            Model = "JYC",
                            Name = "Конденсатор керамический дисковый",
                            Operating_voltage = 2000.0,
                            Part_typeId = 2,
                            Price = 15.0
                        },
                        new
                        {
                            Id = 11,
                            Capacity = 2.2000000000000002,
                            CountryId = 1,
                            ManufacturerId = 3,
                            MaterialId = 4,
                            MaxOperating_Temp = 100,
                            MinOperating_Temp = -40,
                            Name = "Конденсатор бумажный",
                            Operating_voltage = 500.0,
                            Part_typeId = 2,
                            Price = 330.0
                        },
                        new
                        {
                            Id = 12,
                            Capacity = 0.25,
                            CountryId = 4,
                            ManufacturerId = 4,
                            MaterialId = 4,
                            MaxOperating_Temp = 60,
                            MinOperating_Temp = -60,
                            Model = "ОМБГ-3",
                            Name = "Конденсатор бумажный",
                            Operating_voltage = 400.0,
                            Part_typeId = 2,
                            Price = 210.0
                        },
                        new
                        {
                            Id = 13,
                            Capacity = 1.0,
                            CountryId = 2,
                            ManufacturerId = 2,
                            MaterialId = 5,
                            MaxOperating_Temp = 85,
                            MinOperating_Temp = -45,
                            Model = "JFA",
                            Name = "Конденсатор металлоплёночный",
                            Operating_voltage = 100.0,
                            Part_typeId = 2,
                            Price = 10.0
                        },
                        new
                        {
                            Id = 14,
                            Capacity = 180.0,
                            CountryId = 3,
                            ManufacturerId = 10,
                            MaterialId = 5,
                            MaxOperating_Temp = 125,
                            MinOperating_Temp = -60,
                            Model = "полиэстер",
                            Name = "Конденсатор металлоплёночный",
                            Operating_voltage = 63.0,
                            Part_typeId = 2,
                            Price = 33.0
                        },
                        new
                        {
                            Id = 15,
                            Capacity = 65000.0,
                            CountryId = 4,
                            ManufacturerId = 4,
                            MaterialId = 5,
                            MaxOperating_Temp = 65,
                            MinOperating_Temp = -25,
                            Model = "b32320i",
                            Name = "Конденсатор плёночный",
                            Operating_voltage = 350.0,
                            Part_typeId = 2,
                            Price = 1330.0
                        },
                        new
                        {
                            Id = 16,
                            Capacity = 0.012500000000000001,
                            CountryId = 5,
                            ManufacturerId = 5,
                            MaterialId = 5,
                            MaxOperating_Temp = 85,
                            MinOperating_Temp = -25,
                            Model = "tzc3",
                            Name = "Конденсатор подстроечный",
                            Operating_voltage = 100.0,
                            Part_typeId = 3,
                            Price = 200.0
                        },
                        new
                        {
                            Id = 17,
                            Capacity = 0.0022000000000000001,
                            CountryId = 2,
                            ManufacturerId = 6,
                            MaterialId = 3,
                            MaxOperating_Temp = 85,
                            MinOperating_Temp = -25,
                            Model = "tzc3",
                            Name = "Конденсатор подстроечный",
                            Operating_voltage = 100.0,
                            Part_typeId = 3,
                            Price = 280.0
                        },
                        new
                        {
                            Id = 18,
                            CountryId = 2,
                            Electric_current = 0.37,
                            Inductance = 0.01,
                            ManufacturerId = 6,
                            MaterialId = 6,
                            MaxOperating_Temp = 100,
                            MinOperating_Temp = -20,
                            Model = "ec24",
                            Name = "Индуктивный элемент",
                            Part_typeId = 2,
                            Price = 15.0,
                            Resistance = 0.71999999999999997
                        },
                        new
                        {
                            Id = 19,
                            CountryId = 3,
                            Electric_current = 0.20000000000000001,
                            Inductance = 0.047,
                            ManufacturerId = 10,
                            MaterialId = 6,
                            MaxOperating_Temp = 100,
                            MinOperating_Temp = -20,
                            Model = "киг",
                            Name = "Катушка индуктивности",
                            Part_typeId = 2,
                            Price = 110.0,
                            Resistance = 11.0
                        },
                        new
                        {
                            Id = 20,
                            CountryId = 4,
                            Electric_current = 0.025000000000000001,
                            Inductance = 0.01,
                            ManufacturerId = 4,
                            MaterialId = 6,
                            MaxOperating_Temp = 125,
                            MinOperating_Temp = -40,
                            Name = "Катушка индуктивности",
                            Part_typeId = 2,
                            Price = 530.0
                        },
                        new
                        {
                            Id = 21,
                            CountryId = 1,
                            Inductance = 0.01,
                            ManufacturerId = 1,
                            MaterialId = 6,
                            MaxOperating_Temp = 100,
                            MinOperating_Temp = -20,
                            Model = "cm322522",
                            Name = "Индуктивность SMD",
                            Part_typeId = 2,
                            Price = 31.0,
                            Resistance = 2.1000000000000001
                        },
                        new
                        {
                            Id = 22,
                            CountryId = 5,
                            Electric_current = 0.10000000000000001,
                            Inductance = 30.0,
                            ManufacturerId = 5,
                            MaterialId = 6,
                            Model = "bla",
                            Name = "Индуктивность для подавления ЭПМ",
                            Part_typeId = 2,
                            Price = 49.0,
                            Resistance = 600.0
                        },
                        new
                        {
                            Id = 23,
                            CountryId = 5,
                            Electric_current = 0.29999999999999999,
                            Inductance = 36.0,
                            ManufacturerId = 5,
                            MaterialId = 6,
                            MaxOperating_Temp = 60,
                            MinOperating_Temp = -25,
                            Model = "pla",
                            Name = "Фильтр подавления ЭПМ",
                            Operating_voltage = 300.0,
                            Part_typeId = 2,
                            Price = 170.0
                        },
                        new
                        {
                            Id = 24,
                            CountryId = 4,
                            Electric_current = 0.33000000000000002,
                            Inductance = 2.7000000000000002,
                            ManufacturerId = 4,
                            MaterialId = 7,
                            MaxOperating_Temp = 125,
                            MinOperating_Temp = -55,
                            Model = "RF",
                            Name = "Дроссель: проволочный",
                            Part_typeId = 2,
                            Price = 270.0,
                            Resistance = 4.1399999999999997
                        },
                        new
                        {
                            Id = 25,
                            CountryId = 4,
                            Electric_current = 2.0,
                            Inductance = 5.0,
                            ManufacturerId = 4,
                            MaterialId = 7,
                            Model = "b82615",
                            Name = "Дроссель силовой",
                            Operating_voltage = 250.0,
                            Part_typeId = 2,
                            Price = 980.0,
                            Resistance = 0.5
                        },
                        new
                        {
                            Id = 26,
                            CountryId = 4,
                            Electric_current = 5.0,
                            Inductance = 0.25,
                            ManufacturerId = 4,
                            MaterialId = 7,
                            Model = "b82625",
                            Name = "Дроссель",
                            Operating_voltage = 250.0,
                            Part_typeId = 2,
                            Price = 1210.0,
                            Resistance = 0.071999999999999995
                        },
                        new
                        {
                            Id = 27,
                            CountryId = 2,
                            ManufacturerId = 6,
                            MaterialId = 2,
                            MaxOperating_Temp = 155,
                            MinOperating_Temp = -55,
                            Model = "smd 0402",
                            Name = "Чип резистор (SMD)",
                            Operating_voltage = 50.0,
                            Part_typeId = 2,
                            Power = 0.062,
                            Price = 6.0,
                            Resistance = 1.2
                        },
                        new
                        {
                            Id = 28,
                            CountryId = 1,
                            Electric_current = 0.02,
                            ManufacturerId = 1,
                            MaterialId = 8,
                            MaxOperating_Temp = 70,
                            MinOperating_Temp = 0,
                            Name = "Кварцевый генератор",
                            Operating_voltage = 5.0,
                            Part_typeId = 2,
                            Price = 300.0
                        },
                        new
                        {
                            Id = 29,
                            Capacity = 1.5,
                            CountryId = 4,
                            ManufacturerId = 4,
                            MaterialId = 9,
                            MaxOperating_Temp = 110,
                            MinOperating_Temp = -40,
                            Model = "b32022",
                            Name = "Конденсатор подавления ЭМП",
                            Operating_voltage = 300.0,
                            Part_typeId = 2,
                            Price = 50.0
                        },
                        new
                        {
                            Id = 30,
                            Capacity = 1000.0,
                            CountryId = 1,
                            ManufacturerId = 9,
                            MaterialId = 9,
                            MaxOperating_Temp = 125,
                            MinOperating_Temp = -55,
                            Name = "Конденсатор танталовый SMD",
                            Operating_voltage = 35.0,
                            Part_typeId = 2,
                            Price = 28.0
                        },
                        new
                        {
                            Id = 31,
                            CountryId = 2,
                            ManufacturerId = 6,
                            MaterialId = 6,
                            MaxOperating_Temp = 85,
                            MinOperating_Temp = -25,
                            Model = "fscq",
                            Name = "Импульсный регулятор напряжения",
                            Operating_voltage = 650.0,
                            Part_typeId = 1,
                            Power = 210.0,
                            Price = 580.0
                        },
                        new
                        {
                            Id = 32,
                            CountryId = 2,
                            ManufacturerId = 7,
                            MaterialId = 7,
                            MaxOperating_Temp = 150,
                            MinOperating_Temp = -40,
                            Model = "viper",
                            Name = "ШИМ-контроллер со встроенным силовым ключом",
                            Operating_voltage = 730.0,
                            Part_typeId = 1,
                            Power = 8.0,
                            Price = 180.0
                        },
                        new
                        {
                            Id = 33,
                            CountryId = 6,
                            ManufacturerId = 8,
                            MaterialId = 7,
                            MaxOperating_Temp = 85,
                            MinOperating_Temp = -40,
                            Model = "HMC273A",
                            Name = "Аттенюатор",
                            Operating_voltage = 5.0,
                            Part_typeId = 1,
                            Power = 1.0,
                            Price = 2540.0,
                            Resistance = 50.0
                        },
                        new
                        {
                            Id = 34,
                            CountryId = 6,
                            ManufacturerId = 8,
                            MaterialId = 7,
                            MaxOperating_Temp = 85,
                            MinOperating_Temp = -40,
                            Model = "HMC658G",
                            Name = "Аттенюатор",
                            Operating_voltage = 5.0,
                            Part_typeId = 1,
                            Power = 0.316,
                            Price = 2530.0,
                            Resistance = 50.0
                        },
                        new
                        {
                            Id = 35,
                            CountryId = 6,
                            Electric_current = 0.01,
                            ManufacturerId = 8,
                            MaterialId = 6,
                            MaxOperating_Temp = 70,
                            MinOperating_Temp = 0,
                            Model = "AD790JNZ",
                            Name = "Быстродействующий прецизионный компаратор напряжения",
                            Operating_voltage = 4.0,
                            Part_typeId = 1,
                            Price = 2700.0
                        },
                        new
                        {
                            Id = 36,
                            CountryId = 2,
                            Electric_current = 0.0060000000000000001,
                            ManufacturerId = 7,
                            MaterialId = 3,
                            MaxOperating_Temp = 85,
                            MinOperating_Temp = -40,
                            Model = "LM211DT",
                            Name = "Дифференциальный компаратор со стробированием",
                            Operating_voltage = 15.0,
                            Part_typeId = 1,
                            Price = 53.0
                        },
                        new
                        {
                            Id = 37,
                            CountryId = 5,
                            Electric_current = 0.002,
                            ManufacturerId = 5,
                            MaterialId = 3,
                            MaxOperating_Temp = 70,
                            MinOperating_Temp = 0,
                            Model = "LM2901DT",
                            Name = "Маломощный квадрантный компаратор напряжения",
                            Operating_voltage = 15.0,
                            Part_typeId = 1,
                            Price = 34.0
                        },
                        new
                        {
                            Id = 38,
                            Capacity = 5000.0,
                            CountryId = 2,
                            ManufacturerId = 6,
                            MaterialId = 9,
                            MaxOperating_Temp = 70,
                            MinOperating_Temp = -40,
                            Model = "CBB61",
                            Name = "Конденсатор пусковой",
                            Operating_voltage = 450.0,
                            Part_typeId = 2,
                            Price = 240.0
                        },
                        new
                        {
                            Id = 39,
                            CountryId = 1,
                            ManufacturerId = 1,
                            MaterialId = 3,
                            MaxOperating_Temp = 125,
                            MinOperating_Temp = 1,
                            Model = "3540s",
                            Name = "Резистор прецизионный многооборотный",
                            Part_typeId = 2,
                            Power = 2.0,
                            Price = 5700.0,
                            Resistance = 1000.0
                        },
                        new
                        {
                            Id = 40,
                            CountryId = 1,
                            ManufacturerId = 9,
                            MaterialId = 3,
                            MaxOperating_Temp = 70,
                            MinOperating_Temp = -10,
                            Model = "r24n1",
                            Name = "Резистор переменный",
                            Operating_voltage = 500.0,
                            Part_typeId = 2,
                            Power = 0.5,
                            Price = 150.0,
                            Resistance = 1000.0
                        },
                        new
                        {
                            Id = 41,
                            CountryId = 1,
                            ManufacturerId = 9,
                            MaterialId = 3,
                            MaxOperating_Temp = 70,
                            MinOperating_Temp = -10,
                            Model = "rk-1112n",
                            Name = "Резистор переменный",
                            Operating_voltage = 50.0,
                            Part_typeId = 2,
                            Power = 0.050000000000000003,
                            Price = 97.0,
                            Resistance = 1000.0
                        },
                        new
                        {
                            Id = 42,
                            Capacity = 0.012,
                            CountryId = 4,
                            ManufacturerId = 4,
                            MaterialId = 3,
                            MaxOperating_Temp = 125,
                            MinOperating_Temp = -55,
                            Model = "к10-17б",
                            Name = "Конденсатор керамический выводной",
                            Operating_voltage = 50.0,
                            Part_typeId = 2,
                            Price = 7.0
                        },
                        new
                        {
                            Id = 43,
                            CountryId = 1,
                            Electric_current = 0.5,
                            ManufacturerId = 9,
                            MaterialId = 10,
                            MaxOperating_Temp = 85,
                            MinOperating_Temp = -65,
                            Name = "Предохранитель стеклянный быстродействующий",
                            Operating_voltage = 250.0,
                            Part_typeId = 2,
                            Price = 15.0
                        },
                        new
                        {
                            Id = 44,
                            CountryId = 3,
                            Electric_current = 0.63,
                            ManufacturerId = 10,
                            MaterialId = 10,
                            MaxOperating_Temp = 85,
                            MinOperating_Temp = -60,
                            Name = "Предохранитель",
                            Operating_voltage = 250.0,
                            Part_typeId = 2,
                            Price = 30.0
                        },
                        new
                        {
                            Id = 45,
                            CountryId = 3,
                            Electric_current = 5.0,
                            ManufacturerId = 10,
                            MaterialId = 10,
                            MaxOperating_Temp = 100,
                            MinOperating_Temp = -60,
                            Name = "Предохранитель",
                            Operating_voltage = 600.0,
                            Part_typeId = 2,
                            Price = 54.0
                        },
                        new
                        {
                            Id = 46,
                            CountryId = 5,
                            Electric_current = 4.0,
                            ManufacturerId = 5,
                            MaterialId = 3,
                            MaxOperating_Temp = 100,
                            MinOperating_Temp = -60,
                            Name = "Предохранитель керамический",
                            Operating_voltage = 250.0,
                            Part_typeId = 2,
                            Price = 33.0
                        },
                        new
                        {
                            Id = 47,
                            CountryId = 3,
                            Electric_current = 0.10000000000000001,
                            ManufacturerId = 10,
                            MaterialId = 3,
                            MaxOperating_Temp = 70,
                            MinOperating_Temp = -60,
                            Name = "Предохранитель керамический",
                            Operating_voltage = 350.0,
                            Part_typeId = 2,
                            Price = 26.0
                        },
                        new
                        {
                            Id = 48,
                            CountryId = 1,
                            Electric_current = 40.0,
                            ManufacturerId = 1,
                            MaterialId = 3,
                            MaxOperating_Temp = 85,
                            MinOperating_Temp = -40,
                            Model = "MF-R020",
                            Name = "Предохранитель самовосстанавливающийся",
                            Operating_voltage = 60.0,
                            Part_typeId = 2,
                            Power = 0.40000000000000002,
                            Price = 38.0,
                            Resistance = 2.2000000000000002
                        },
                        new
                        {
                            Id = 49,
                            CountryId = 1,
                            Electric_current = 2.0,
                            ManufacturerId = 1,
                            MaterialId = 6,
                            MaxOperating_Temp = 125,
                            MinOperating_Temp = -55,
                            Model = "SF-1206SxxxM",
                            Name = "Плавкий предохранитель",
                            Operating_voltage = 63.0,
                            Part_typeId = 2,
                            Price = 130.0,
                            Resistance = 50.0
                        },
                        new
                        {
                            Id = 50,
                            CountryId = 1,
                            ManufacturerId = 1,
                            MaterialId = 2,
                            MaxOperating_Temp = 155,
                            MinOperating_Temp = -55,
                            Model = "CF-50",
                            Name = "Резистор углеродистый",
                            Operating_voltage = 350.0,
                            Part_typeId = 2,
                            Power = 0.5,
                            Price = 9.0,
                            Resistance = 510.0
                        });
                });

            modelBuilder.Entity("BD.Models.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Activity")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<string>("Director")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activity = "Electronics",
                            Address = "Риверсайд, Калифорния",
                            Country = "США",
                            Director = "Гордон Борнс",
                            Name = "BOURNS"
                        },
                        new
                        {
                            Id = 2,
                            Activity = "Electronics",
                            Address = "г. Хэфей, провинция Аньхой, КНР; г. Дунгуан, провинция Гуаньдун.",
                            Country = "Китай",
                            Name = "JB Capacitors",
                            Phone = "+8-522-790-50-91"
                        },
                        new
                        {
                            Id = 3,
                            Activity = "Electronics",
                            Address = "Форт-Лодердейл, Флорида",
                            Country = "США",
                            Name = "Kemet Electronics"
                        },
                        new
                        {
                            Id = 4,
                            Activity = "Electronics",
                            Address = "Мюнхен",
                            Country = "Германия",
                            Name = "EPCOS"
                        },
                        new
                        {
                            Id = 5,
                            Activity = "Electronics",
                            Address = "Нагаокакё, Киото",
                            Country = "Япония",
                            Director = "Норио Накадзима",
                            Name = "Murata Electronics"
                        },
                        new
                        {
                            Id = 6,
                            Activity = "Electronics",
                            Address = " Финикс, Аризона",
                            Country = "США",
                            Director = "Хассан Эль-Хури",
                            Name = "ON Semiconductor"
                        },
                        new
                        {
                            Id = 7,
                            Activity = "Electronics",
                            Address = "Женева",
                            Country = "Швейцария",
                            Director = "Жан-Марк Чери, Remi El-Ouazzane",
                            Name = "STMicroelectronics"
                        },
                        new
                        {
                            Id = 8,
                            Activity = "Semiconductor",
                            Address = "Уилмингтон, Массачусетс",
                            Country = "США",
                            Director = "Венсан Рош",
                            Name = "Analog Devices"
                        },
                        new
                        {
                            Id = 9,
                            Activity = "Electronics",
                            Address = "4F-1, № 288-7, ShinYa Road, район Чиен Чен, Гаосюн, 80673",
                            Country = "Тайвань",
                            Name = "Song Huei Electronic",
                            Phone = "+8-867-815-00-38"
                        },
                        new
                        {
                            Id = 10,
                            Activity = "Electronics",
                            Address = "431110, Республика Мордовия, п. Зубова Поляна, ул. Новикова-Прибоя, 35.",
                            Country = "Россия",
                            Director = "Казеев Александр Александрович",
                            Name = "ОАО \"Радиодеталь\"",
                            Phone = "+7-834-582-11-50"
                        });
                });

            modelBuilder.Entity("BD.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Materials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = 1,
                            Name = "Металлокерамика"
                        },
                        new
                        {
                            Id = 2,
                            Code = 2,
                            Name = "Углерод"
                        },
                        new
                        {
                            Id = 3,
                            Code = 3,
                            Name = "Керамика"
                        },
                        new
                        {
                            Id = 4,
                            Code = 4,
                            Name = "Бумага"
                        },
                        new
                        {
                            Id = 5,
                            Code = 5,
                            Name = "Плёнка"
                        },
                        new
                        {
                            Id = 6,
                            Code = 6,
                            Name = "Медь"
                        },
                        new
                        {
                            Id = 7,
                            Code = 7,
                            Name = "Феррит"
                        },
                        new
                        {
                            Id = 8,
                            Code = 8,
                            Name = "Кварц"
                        },
                        new
                        {
                            Id = 9,
                            Code = 9,
                            Name = "Полипропилен"
                        },
                        new
                        {
                            Id = 10,
                            Code = 10,
                            Name = "Стекло"
                        });
                });

            modelBuilder.Entity("BD.Models.RssItem", b =>
                {
                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PubDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("RssItems");
                });

            modelBuilder.Entity("BD.Models.RssLink", b =>
                {
                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("RssLinks");
                });

            modelBuilder.Entity("BD.Models.Type", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Types");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = 1,
                            Name = "Активный"
                        },
                        new
                        {
                            Id = 2,
                            Code = 2,
                            Name = "Пассивный"
                        },
                        new
                        {
                            Id = 3,
                            Code = 3,
                            Name = "Подстроечный"
                        });
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BD.Models.Details", b =>
                {
                    b.HasOne("BD.Models.Country", "Country")
                        .WithMany("Details")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BD.Models.Manufacturer", "Manufacturer")
                        .WithMany("Details")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BD.Models.Material", "Material")
                        .WithMany("Details")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BD.Models.Type", "Part_type")
                        .WithMany("Details")
                        .HasForeignKey("Part_typeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Manufacturer");

                    b.Navigation("Material");

                    b.Navigation("Part_type");
                });

            modelBuilder.Entity("BD.Models.Country", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("BD.Models.Manufacturer", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("BD.Models.Material", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("BD.Models.Type", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
